version: "3.8"
services:
  db:
    image: mysql:5.7
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app-for-try-rails
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
  sidekiq:
    build: .
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - .:/app-for-try-rails
  redis:
    image: redis:latest
    ports:
      - "6370:6379"
    volumes:
      - ./data/redis:/data
volumes:
  dbvolume:
  gem_data:
  redis:
