version: "3.8"
services:
  db:
    image: mysql:5.7
    # データの永続化の為に使用
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    # Mac(M1)を使用している場合、platformに関するエラーが発生する可能性がある。エラー発生してから追加するのも良し。
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  app:
    # 作成済みのDockerfileを元にコンテナを作成
    build:
      # Dockerfileでファイルの読み込み先を指定
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app-for-try-rails
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    # コンテナの立ち上げ順と依存関係を指定。dbコンテナが立ち上がってからappコンテナが立ち上がるようにする。
    depends_on:
      - db
    # stdin_open, ttyは`pry-byebug`を使用するために記述
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
  sidekiq:
    build: .
    env_file:
      - .env
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - .:/app-for-try-rails
  redis:
    image: redis:latest
    ports:
      - "6370:6379"
    volumes:
      - ./data/redis:/data
volumes:
  dbvolume:
  gem_data:
  redis:
