name: rspec

# masterブランチへのPR時の実行
on:
  pull_request:
    branches:
    - development
    # ex.
    # # Trigger the workflow on push or pull request
    # on: [push, pull_request]
    # # Trigger the workflow on pull request activity
    # on:
    #   release
    #     # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    #     types: [published, created, edited]

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    defaults:
      run:
        working-directory: backend # ディレクトリを指定 (runに適用される)
    services:
      mysql:　 # テスト用データベースの設定
        image: mysql:8.0.29
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes # パスワード空を許可
          BIND-ADDRESS: 0.0.0.0
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10 #ヘルスチェック
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
          bundler-cache: true # キャッシュの設定
          working-directory: backend # ディレクトリを指定 (ここでも指定しないとキャッシュされない)
      - name: Run migration
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run RSpec
        run: bundle exec rspec
