name: Run rspec
on: [pull_request]
jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services: # サービスコンテナをホストするらしい。DBやRedisとかを使うときに宣言する。
      mysql: # service_id
        image: mysql:8.0 # Docker Hubのイメージ
        ports: # サービスコンテナーで公開するポート
          - 3306:3306
        env: # 環境変数
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo "ths is env=$GOOGLE_MAP_API_KEY"
          echo "GOOGLE_MAP_API_KEY=$GOOGLE_MAP_API_KEY" >> $GITHUB_ENV
        env:
          GOOGLE_MAP_API_KEY: "hoge"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        run: bundle lock --add-platform x86_64-linux
        with:
          bundler-cache: true

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Yarn install
        run: yarn install --check-files

      - name: Database create and migrate
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run rspec
        run: bundle exec rspec
